---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventorymgmtdb
    username: root
    password: J@imathadi12
  config:
   activate:
    on-profile: dev
store:
  slaDays: 100
  transportType: roadways
  jpa:
    show-sql: true
    generate-ddl: false    
stock:
  transportType: air5
  slaDays: 100 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka    
...
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventorymgmtdb
    username: root
    password: J@imathadi12
  config:
   activate:
    on-profile: test
store:
  slaDays: 100
  transportType: roadways
  jpa:
    show-sql: true
    generate-ddl: false    
stock:
  transportType: air6
  slaDays: 200 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka 
...      